version: "3"
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    image: easychat-api
    container_name: easychat-api
    command: npm start
    ports:
      - 3000:3000
    depends_on:
      - rethinkdb

  rethinkdb:
    container_name: rethinkdb
    image: rethinkdb
    volumes:
      - ./data:/data/db
    ports:
      - 8080:8080
      - 28015:28015
      - 29015:29015


