version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - 3000:3000
    links:
      - rethinkdb
  rethinkdb:
    container_name: rethinkdb
    image: rethinkdb
    volumes:
      - ./data:/data/db
    ports:
      - 8080:8080
      - 28015:28015
      - 29015:29015
